[tool.poetry]
name = "score"
version = "0.1.0"
description = ""
authors = ["eundata <tupce2@naver.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.43.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
